# frozen_string_literal: true

source "https://rubygems.org"

gem "allure-cucumber", "2.13.6.4"
gem "cucumber", "5.2"
gem "capybara", "~> 3.35", ">= 3.35.2"
gem "rspec", "3.8.0"
gem "selenium-webdriver", "3.142.0"
gem "faker"
gem "ffaker"
